"use client";
import "./globals.css";
import { Inter, Josefin_Sans, Poppins } from "next/font/google";
import { ThemeProvider } from "./utils/theme-provider";
import { Toaster } from "react-hot-toast";
import { Providers } from "./Provider";
import "../i18n"; // Import i18n để khởi tạo đa ngôn ngữ
import { SessionProvider } from "next-auth/react";
import React, { useEffect, useState, useRef } from "react";
import Loader from "./components/Loader/Loader";
import { useLoadUserQuery } from "@/redux/features/api/apiSlice";
import ErrorBoundary from "./hooks/errorBoundary";
import { joinUserRoom } from "./utils/socket";
import { useSelector } from "react-redux";
import ChatBox from "./components/Chat/ChatBox";
  

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-poppins",
});

const josefin = Josefin_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-Josefin",
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} ${josefin.variable} !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black duration-300`}
            >
                <Providers>
                    <SessionProvider>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                            <Custom>{children}</Custom>

                            <Toaster position="top-center" reverseOrder={false} />
                        </ThemeProvider>
                    </SessionProvider>
                </Providers>
            </body>
        </html>
    );
}
const Custom: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { isLoading, data: userData } = useLoadUserQuery({});
    const [isClient, setIsClient] = useState(false);
    const auth = useSelector((state: any) => state.auth);
    const joinedUserIdRef = useRef<string | null>(null);

    useEffect(() => {
        setIsClient(true); // Đảm bảo chỉ render Loader trên client
    }, []);

    // Auto join socket room when user is logged in
    // Only join once per userId to avoid multiple calls on re-render
    useEffect(() => {
        if (!isClient) return;

        const userId = auth?.user?._id || userData?.user?._id;
        
        // Only join if we have a userId and it's different from the one we already joined
        if (userId && userId !== joinedUserIdRef.current) {
            console.log(`[LAYOUT] 👤 Auto-joining socket room for user: ${userId}`);
            joinedUserIdRef.current = userId;
            joinUserRoom(userId);
        }
    }, [auth?.user?._id, userData?.user?._id, isClient]);

    // Reset joinedUserId when user logs out
    useEffect(() => {
        const userId = auth?.user?._id || userData?.user?._id;
        if (!userId && joinedUserIdRef.current) {
            joinedUserIdRef.current = null;
        }
    }, [auth?.user?._id, userData?.user?._id]);

    if (!isClient) {
        return null; // Trả về null trên server để tránh lỗi hydration
    }
    return (
        <>
            <ErrorBoundary>{isLoading ? <Loader /> : <>{children}</>}</ErrorBoundary>
            <ChatBox />
        </>
    );
};
